default:
  image: registry.miti.chat/miti/miti-go:1.0.1
  before_script:
    - export BRANCH_NAME="${CI_COMMIT_REF_NAME//\//_}"
    - export OUT_PUT_FILE="${CI_PROJECT_NAME}.${BRANCH_NAME}"
    - echo ${REMOTE_MACHINE}    
    - git config --global url."https://oauth2:${GITLAB_ACCESS_TOKEN}@repo.miti.chat".insteadOf "https://repo.miti.chat"
    
  cache:
    paths:
      - build/app/outputs/flutter-apk/

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - flutter build apk
  artifacts:
    name: "${OUT_PUT_FILE}"
    paths:
      - build/app/outputs/flutter-apk/*.apk

deploy:
  stage: deploy
  script: 
    # 传输文件
    - scp -rv build/app/outputs/flutter-apk/*.apkr ${REMOTE_MACHINE}:/home/ubuntu/download/apks

