name: miti_circle
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: 5.8.4
  get: ^4.6.5
  search_keyword_text: ^0.0.2
  sprintf: ^7.0.0
  common_utils: ^2.1.0
  wechat_assets_picker: ^8.4.0
  wechat_camera_picker: any
  device_info_plus: ^9.1.0
  chewie: ^1.7.5
  video_player: ^2.8.2
  flutter_cache_manager: ^3.3.0
  pull_to_refresh: ^2.0.0
  animate_do: ^3.0.2
  uuid: ^4.2.1
  cached_network_image: ^3.3.1
  flutter_background: ^1.2.0
  miti_common:
    path: ../miti_common
  flutter_openim_sdk:
    path: ../flutter_openim_sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  # extended_image: ^8.2.0
  # fixed滑动和放大手势冲突, 基于8.2.0
  extended_image:
    git:
      url: https://github.com/bpquanttech/extended_image.git
      ref: v8.2.0-fixed

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
