// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuplML7U8PxiqUg_xMrPG_Rdnvw9NAXHY',
    appId: '1:431976415575:android:00cc41930e51a636e63e12',
    messagingSenderId: '431976415575',
    projectId: 'miti-2e347',
    storageBucket: 'miti-2e347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpMDPXXHNYwvM7M55jB-YLet49Rf2nok',
    appId: '1:431976415575:ios:44c6eb147457d759e63e12',
    messagingSenderId: '431976415575',
    projectId: 'miti-2e347',
    storageBucket: 'miti-2e347.appspot.com',
    androidClientId:
        '431976415575-45i7ffficml1ckt8e5761su7bo6l0u5n.apps.googleusercontent.com',
    iosClientId:
        '431976415575-9ubb0tk0ftgc7e8qp16neholl9mpjt49.apps.googleusercontent.com',
    iosBundleId: 'chat.miti.ios.NotificationService',
  );
}
